allOf:
  - $ref: ./ResourceBase.yaml
  - type: object
    required:
      - Profile
      - Limits
      - Resources
      - PermittedSites
      - PermittedOSImages
      - VolumeReplicationEnabled
      - BootFromSANSupport
    properties:
      Profile:
        description: Profile is a generalized description of a team.
        $ref: ./Profile.yaml
      Limits:
        description: >-
          Project Limits place general constraints on a project in terms of
          server and storage.
        $ref: ./Limits.yaml
      Resources:
        description: Project resources provides resources currently utilized by the project.
        $ref: ./ProjectResources.yml
      PermittedSites:
        description: Array listing the permitted site IDs
        type: array
        items:
          type: string
          format: uuid
        example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 91eec8b5-6460-4532-aad1-47b983edb63c
      PermittedOSImages:
        description: Array listing the permitted OS service images.
        type: array
        items:
          type: string
          format: uuid
        example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 91eec8b5-6460-4532-aad1-47b983edb63c
      VolumeReplicationEnabled:
        type: boolean
        description: Indicates whether volume replication is enabled for this Project.
      ParentID:
        type: string
        description: ID of the Parent Project (optional). Applicable to GreenLake Platform (GLP) only.
      BootFromSANSupport:
        type: boolean
        description: Indicates whether Boot-from-SAN feature support is enabled for this Project.
