// (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

// Code generated by ifacemaker; DO NOT EDIT.

package client

import (
	_context "context"
	_nethttp "net/http"
)

// VersionAPI defines the client functions provided for Version.
type VersionAPI interface {
	/*
	   Get Get api server build version
	     - @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().

	   @return Version
	*/
	Get(ctx _context.Context) (Version, *_nethttp.Response, error)
}
