// (C) Copyright 2021 Hewlett Packard Enterprise Development LP

/*
 * Quake Project Client API
 *
 * This Quake client REST API provides access to bare metal as-a-service (BMaaS) within a single project context.  Clients are able to create fully-provisioned hosts, storage volumes, and project-specific private networks in an isolated project environment.  Project-owned resources that can be accessed via this API include... Host, Volume, VolumeAttachment, Network (project private), and SSH Key.    Each API call is done within a single project context.  The specific Project identifier must be provided within the header of each REST call. The server will validate that the provided authentication credentials (JWTs) are valid for the referenced project before any operation is performed.  If a single credential is valid for multiple projects, the client must still reference a single project in the header each API call.  Clients can also access information about available services and resources through the AvailableResources object.  This object provides detailed  information about the OS imaging options, the machine size options, the storage volume options, data center locations, and such that are needed when creating hosts and volumes. 
 *
 * API version: 1.3.1
 * Contact: quake-core@hpe.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"time"
)
// VolumeAttachment struct for VolumeAttachment
type VolumeAttachment struct {
	// Unique ID for the resource instance as generated by the Quake service
	ID string `json:"ID,omitempty"`
	// Used to determine whether the DB entry has changed since it was last read.  should be returned unchanged on any update operation.
	ETag string `json:"ETag,omitempty"`
	// Common name for the resource instance
	Name string `json:"Name,omitempty"`
	// Time when the resource was created in the database
	Created time.Time `json:"Created,omitempty"`
	// Time when the resource was last modified in the database
	Modified time.Time `json:"Modified,omitempty"`
	// Unique ID of the volume attached to the host
	VolumeID string `json:"VolumeID,omitempty"`
	// Unique ID of the host connected to the volume
	HostID string `json:"HostID,omitempty"`
	// Host IP address for the network connection that connects to the storage array
	HostIPAddress string `json:"HostIPAddress,omitempty"`
	// IQN is the full initiator name used for identification during iSCSI login
	IQN string `json:"IQN,omitempty"`
	// CHAPSecret is the Challenge Authentication Protocol secret to be shared between array and initiator.
	CHAPSecret string `json:"CHAPSecret,omitempty"`
	// CHAPUserName is the CHAP username to use for CHAP authentication
	CHAPUserName string `json:"CHAPUserName,omitempty"`
	// LUN is the Logical Unit Number to be assigned to the volume on export
	LUN uint32 `json:"LUN,omitempty"`
	// VolumeTargetIQN is the iQN for the volume, assigned by the array correspnding to the volume
	VolumeTargetIQN string `json:"VolumeTargetIQN,omitempty"`
	// VolumeTargetIPAddress is the IPV4 address of the iSCSI volume export
	VolumeTargetIPAddress string `json:"VolumeTargetIPAddress,omitempty"`
}
