// (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

/*
 * HPE GreenLake for bare metal API
 *
 * This Metal Client REST API provides access to bare metal as-a-service (BMaaS) within a single project context. Clients are able to create fully-provisioned hosts, storage volumes, and project-specific private networks in an isolated project environment.   Project-owned resources that can be accessed via this API include - Host,  Volume, VolumeAttachment, Network (project private), and SSH Key. Each API  call is done within a single project context. The specific Project identifier  must be provided within the header of for each REST call. The server will  validate that the provided authentication credentials (JWTs) are valid  for  the referenced project before any operation is performed. If a single credential is valid for multiple projects, the client must still reference a single project  in the header for each API call.    Clients can also access information about available services and resources through the AvailableResources object. This object provides detailed  information about the OS imaging options, the machine size options, the storage volume options, and data center locations which are needed when creating hosts and volumes.  
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
// PartitionType It defines the available partition types. This should be defined to correspond to target OS known partition types (as known by name on that OS).
type PartitionType string

// List of PartitionType
const (
	PARTITIONTYPE_SWAP PartitionType = "swap"
	PARTITIONTYPE_EXT2 PartitionType = "ext2"
	PARTITIONTYPE_EXT3 PartitionType = "ext3"
	PARTITIONTYPE_EXT4 PartitionType = "ext4"
	PARTITIONTYPE_XFS PartitionType = "xfs"
	PARTITIONTYPE_BTRFS PartitionType = "btrfs"
	PARTITIONTYPE_VFAT PartitionType = "vfat"
	PARTITIONTYPE_BIOS PartitionType = "bios"
	PARTITIONTYPE_BASIC PartitionType = "basic"
	PARTITIONTYPE_LVM PartitionType = "lvm"
	PARTITIONTYPE_LUKS PartitionType = "luks"
	PARTITIONTYPE_VMDIAG PartitionType = "vmdiag"
	PARTITIONTYPE_VMFS PartitionType = "vmfs"
)
