// (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

// (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP

// Code generated by MockGen. DO NOT EDIT.
// Source: interface_images.go

// Package mockquakeclient is a generated GoMock package.
package mockquakeclient

import (
	context "context"
	http "net/http"
	os "os"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "github.com/hewlettpackard/hpegl-metal-client/v1/pkg/client"
)

// MockImagesAPI is a mock of ImagesAPI interface.
type MockImagesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockImagesAPIMockRecorder
}

// MockImagesAPIMockRecorder is the mock recorder for MockImagesAPI.
type MockImagesAPIMockRecorder struct {
	mock *MockImagesAPI
}

// NewMockImagesAPI creates a new mock instance.
func NewMockImagesAPI(ctrl *gomock.Controller) *MockImagesAPI {
	mock := &MockImagesAPI{ctrl: ctrl}
	mock.recorder = &MockImagesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImagesAPI) EXPECT() *MockImagesAPIMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockImagesAPI) Add(ctx context.Context, fileName *os.File, localVarOptionals *client.ImagesApiAddOpts) (client.OsServiceImage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, fileName, localVarOptionals)
	ret0, _ := ret[0].(client.OsServiceImage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Add indicates an expected call of Add.
func (mr *MockImagesAPIMockRecorder) Add(ctx, fileName, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockImagesAPI)(nil).Add), ctx, fileName, localVarOptionals)
}

// Delete mocks base method.
func (m *MockImagesAPI) Delete(ctx context.Context, imageId string) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, imageId)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockImagesAPIMockRecorder) Delete(ctx, imageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockImagesAPI)(nil).Delete), ctx, imageId)
}

// GetByID mocks base method.
func (m *MockImagesAPI) GetByID(ctx context.Context, imageId string) (client.OsServiceImage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, imageId)
	ret0, _ := ret[0].(client.OsServiceImage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetByID indicates an expected call of GetByID.
func (mr *MockImagesAPIMockRecorder) GetByID(ctx, imageId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockImagesAPI)(nil).GetByID), ctx, imageId)
}

// List mocks base method.
func (m *MockImagesAPI) List(ctx context.Context, localVarOptionals *client.ImagesApiListOpts) ([]client.OsServiceImage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, localVarOptionals)
	ret0, _ := ret[0].([]client.OsServiceImage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockImagesAPIMockRecorder) List(ctx, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockImagesAPI)(nil).List), ctx, localVarOptionals)
}

// Update mocks base method.
func (m *MockImagesAPI) Update(ctx context.Context, imageId string, fileName *os.File) (client.OsServiceImage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, imageId, fileName)
	ret0, _ := ret[0].(client.OsServiceImage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Update indicates an expected call of Update.
func (mr *MockImagesAPIMockRecorder) Update(ctx, imageId, fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockImagesAPI)(nil).Update), ctx, imageId, fileName)
}
