allOf:
  - $ref: ./ResourceBase.yaml
  - type: object
    required:
      - profile
      - limits
    properties:
      profile:
        description: Profile is a generalized description of a team
        $ref: ./Profile.yaml
      limits:
        description: >-
          Project Limits place general constraints on a project in terms of
          server and storage
        $ref: ./Limits.yaml
      resources:
        description: Project resources provides resources currently utilized by the project
        $ref: ./ProjectResources.yml
      permittedSites:
        description: Array listing the permitted site IDs
        type: array
        items:
          type: string
          format: uuid
        example:
          - 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - 91eec8b5-6460-4532-aad1-47b983edb63c

