#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [push]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Validate OpenAPI Spec file
        run: (cd v1 && make validate)

      - name: Generate Client and Interfaces
        run: (cd v1 && make verify_gen)
