#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: ci

on: [push]
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2

      - name: Install OpenAPI Generator
        run: npm install @openapitools/openapi-generator-cli@cli-4.2.3 -g

      - name: Validate OpenAPI Spec file
        run: (cd v1 && make validate)

      - name: Generate Client and Interfaces
        run: (cd v1 && make verify_gen)
