#(C) Copyright 2022 Hewlett Packard Enterprise Development LP

name: HTML Doc

on:
  pull_request_target:

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 2
      -
        run: |
          # ensure ref checked out is at the correct sha
          git reset --hard ${PR_SHA}
          # retrieve target branch
          git fetch --no-tags --prune --depth=1 https://x-access-token:${GITHUB_TOKEN}@github.com/${REPOSITORY} +refs/heads/${BASE_REF}:refs/remotes/origin/${BASE_REF}
          git branch ${BASE_REF} origin/${BASE_REF}
          git -c credential.https://github.com/.helper="! f() { echo username=x-access-token; echo password=$GITHUB_TOKEN; };f" remote set-head origin -a
          git config --global --add safe.directory $PWD
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2       

      - name: Install dependencies
        run: |
          # redocly CLI
          npm i -g redoc-cli  
          # yq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq 
          chmod +x yq
          export PATH=${PATH}:`pwd`
      
      - name: Generate HTML doc 
        run: (cd v1 && make gen-html)

      - name: Commit changes
        run: .github/workflows/commit-changes.sh 
        env:
          WATCH_DIR: "v1/html"
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
          GIT_COMMIT_MESSAGE: |
            [auto generated] Checking in generated offline HTML doc
          BRANCH_REF: ${{ github.event.pull_request.head.ref }}
          REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
